name: Build docker image and run node tests

on:
  push:
    branches: [ develop, main ]

jobs:
  build-docker:
    runs-on: [self-hosted, linux, X64, hc]

    outputs:
      image_tag: ${{ steps.setvars.outputs.image_tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set variables
        id: setvars
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          if [[ "${{github.base_ref}}" == "main" || "${{github.ref}}" == "refs/heads/main" ]]; then
            echo "::set-output name=image_tag::latest"
            # echo "::set-output name=dbg::0"
          else
            echo "::set-output name=image_tag::develop"
            # echo "::set-output name=dbg::1"
          fi

      - name: Submodule init
        run: |
          git submodule init
          git submodule update

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Executor
        id: docker_build_executor
        uses: docker/build-push-action@v2
        with:
          # build-args: |
          #   dbg=${{ steps.setvars.outputs.dbg }}
          context: .
          file: Dockerfile-GHA
          platforms: linux/amd64
          push: true
          target: executor
          tags: |
            hermeznetwork/zkevm-prover:${{ steps.setvars.outputs.sha_short }}

      - name: Build and push Full Prover
        id: docker_build_prover
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile-GHA
          platforms: linux/amd64
          push: true
          target: prover
          tags: |
            hermeznetwork/zkevm-prover:${{ steps.setvars.outputs.sha_short }}-prover

      - name: Push Prover to ECR
        id: ecr_push
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
          region: eu-west-1
          local-image: ${{ steps.docker_build_prover.outputs.imageid }}
          image: public.ecr.aws/v2p3f1r8/zkevm-prover:${{ steps.setvars.outputs.sha_short }}-prover

  # node-tests:
  #   needs: build-docker
  #   uses: 0xPolygonHermez/zkevm-node/.github/workflows/test-from-prover.yml@develop
  #   with:
  #     prover_image: hermeznetwork/zkevm-prover:${{needs.build-docker.outputs.image_tag}}"
  #   secrets:
  #     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  #     DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
